### ISSUE TITLE
SecurityUser cannot be cast to User

### ISSUE THREAD

**Issue by ikozlovone** [sivalabs/spring-boot-java-rest-api-secure-archetype#1]
`java.lang.ClassCastException: com.myapp.security.SecurityUser cannot be cast to com.myapp.entity.User
        at com.myapp.web.controller.AuthenticationController.createAuthenticationToken(AuthenticationController.java:57)
        at com.myapp.web.controller.AuthenticationController$$FastClassBySpringCGLIB$$daea3739.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at com.myapp.web.controller.AuthenticationController$$EnhancerBySpringCGLIB$$f4bdb99.createAuthenticationToken(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

```
{
    "timestamp": "2020-04-19T15:41:48.770+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "com.myapp.security.SecurityUser cannot be cast to com.myapp.entity.User",
    "path": "/api/auth/login"
}
```

**Comment by sivaprasadreddy** [comment]
That's a bug..It should be cast to **SecurityUser** instead of **User**. Then we should get  domain **User** object from **securityUser.getName()** which is emailId.

**Comment by ArjunDandagi** [comment]
Thanks for not closing the issue 😂 i was facing the same issue :)
